widget
~~~~~~

**tip**: ``string`` **privzeto**: ``choice``

Osnovni način pri katerem bi moralo biti to polje izpisano. Lahko je eden izmed sledečih:

* ``choice``: izpiše tri vnosna select polja. Vrstni red izbirnikov je definiran
  v opciji `format`_.

* ``text``: izpiše tri vnosna polja ali tip ``text`` (mesec, dan, leto).

* ``single_text``: izpiše en vnos tipa ``date``. Uporabnikov vnos je
  preverjen na osnovi opcije `format`_.
