inherit_data
~~~~~~~~~~~~

.. versionadded:: 2.3
    Opcija ``inherit_data`` je bila predstavljena v Symfony 2.3. Pred tem je bila
    poznana kot ``virtual``.

**tip**: ``boolean`` **privzeto**: ``false``

Ta opcija določa, če bo obrazec dedoval podatke iz svojega starševskega obrazca.
To je lahko uporabno, če imate set polj, ki so duplicirana med
večimi obrazci. Glejte :doc:`/cookbook/form/inherit_data_option`.
