Značka select, potrditvena polja in radio gumbi
-----------------------------------------------

To polje je lahko izpisano kot eno izmed večih različnih HTML polj, odvisno
od opcij ``expanded`` in ``multiple``:

+------------------------------------------+----------+----------+
| tip elementa                             | razširjen| multiple |
+==========================================+==========+==========+
| select značka                            | false    | false    |
+------------------------------------------+----------+----------+
| select značka (z ``multiple`` atributom) | false    | true     |
+------------------------------------------+----------+----------+
| radio gumbi                              | true     | false    |
+------------------------------------------+----------+----------+
| potrditvena polja                        | true     | true     |
+------------------------------------------+----------+----------+
