* **Opcije nastavitev**

  Ste se kdaj spraševali, katere opcije nastavitev imate na voljo v datotekah
  kot je ``app/config/config.yml``? V tej sekciji, so vse nastavitve, ki so na voljo,
  zazčlenjene po ključih (npr. ``framework``), ki definirajo vsako možno
  sekcijo vaših Symfony2 nastavitev.

  * :doc:`framework </reference/configuration/framework>`
  * :doc:`doctrine </reference/configuration/doctrine>`
  * :doc:`security </reference/configuration/security>`
  * :doc:`assetic </reference/configuration/assetic>`
  * :doc:`swiftmailer </reference/configuration/swiftmailer>`
  * :doc:`twig </reference/configuration/twig>`
  * :doc:`monolog </reference/configuration/monolog>`
  * :doc:`web_profiler </reference/configuration/web_profiler>`

* :doc:`Configuring the Kernel (e.g. AppKernel) </reference/configuration/kernel>`

* **Obrazci in preverjanje**

  * :doc:`Reference tipov polj obrazca </reference/forms/types>`
  * :doc:`Reference omejitev potrjevanja </reference/constraints>`
  * :doc:`Reference Twig funkcij predlog in spremenljivk </reference/forms/twig_reference>`

* :doc:`Reference Twig razširitev (obrazci, filtri, značke itd.)  </reference/twig_reference>`

* **Ostala področja**

  * :doc:`/reference/dic_tags`
  * :doc:`/reference/requirements`
