* **Koda**

  * :doc:`Hrošči </contributing/code/bugs>`
  * :doc:`Popravki </contributing/code/patches>`
  * :doc:`Varnost </contributing/code/security>`
  * :doc:`Testi </contributing/code/tests>`
  * :doc:`Kodni standardi </contributing/code/standards>`
  * :doc:`Konvencije kode </contributing/code/conventions>`
  * :doc:`Git </contributing/code/git>`
  * :doc:`Licenca </contributing/code/license>`

* **Dokumentacija**

  * :doc:`Pregled </contributing/documentation/overview>`
  * :doc:`Format </contributing/documentation/format>`
  * :doc:`Standardi dokumentacije </contributing/documentation/standards>`
  * :doc:`Prevodi </contributing/documentation/translations>`
  * :doc:`Licenca </contributing/documentation/license>`

* **Skupnost**

  * :doc:`Proces izdaj </contributing/community/releases>`
  * :doc:`IRC sestanki </contributing/community/irc>`
  * :doc:`Ostali viri </contributing/community/other>`
